language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  
branches:
  only:
    - master
    - working

before_script:
  - composer install --prefer-source

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - jamie.hannaford@rackspace.com
    - glen.campbell@rackspace.com
    - shaunak.kashyap@rackspace.com